### ISSUE TITLE
API v1 vs v2

### ISSUE THREAD

**Issue by alloy** [artsy/omniauth-artsy#4]
Currently this gem [assumes API v1](https://github.com/artsy/omniauth-artsy/blob/da892378e2363b70e20600e7ff8ab44df1dd2bee/lib/omniauth/strategies/artsy.rb#L28). This is slightly counter-intuitive, if the idea is for people outside of Artsy to be able to use this as well, as outsiders can’t register API v1 applications.

I don’t know if that _is_ the idea at all, just assuming as this repo is public, but, if that’s the idea, then I suggest we make the API version configurable and default to v2, which is what people would be using if they register their application through https://developers.artsy.net/client_applications.

**Comment by dblock** [comment]
This is fixed via #5.
